# This workflow is disabled and will not trigger deployments to Vercel.
# To re-enable, change the branch name in 'on.push.branches' to 'main' or another active branch.
name: Deploy to Vercel

on:
  push:
    branches:
      - do-not-deploy-vercel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          # Ensure that VERCEL_PROJECT_ID is set in your repository secrets at https://github.com/<owner>/<repo>/settings/secrets/actions
          working-directory: .
          vercel-args: '--prod'

